<?php foreach($this->articleList as $article):?>
<div>
<?php //echo $this->showArticle($article); ?>
<p><a href="<?php echo $this->url(array('module' => 'hsg', 'controller' => 'index', 'action' => 'show', 'id' => $article->getId())); ?>">weiter lesen</a></p>
</div>
<?php endforeach; ?>
<div class="box info center">
<?php echo $this->paginate(array('module' => 'hsg', 'controller' => 'index', 'action' => 'category', 'id' => $this->category->getId()), $this->pageHandling); ?>
</div>
